# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-SDDL
version:      0.06
version_from: lib/Win32/SDDL.pm
installdirs:  site
requires:
    Test::More:                    0
    Win32::OLE:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
